### ISSUE TITLE
Not working on ios 17.6.1

### ISSUE THREAD

**Issue by Rpipey** [starzia/Footwork#2]
App won’t open. 
please fix as ii is the only decent footwork app in the App Store!

**Comment by starzia** [comment]
Ah, I'm sorry to hear this. I will get to this in about one week, hopefully with an update in the App store within two weeks from now.

**Comment by Rpipey** [comment]
Fabulous, thanks.
I've tried others but none are as good as yours!

**Comment by starzia** [comment]
Please update to the v3.2 version of the app which was posted this morning.

**Comment by Rpipey** [comment]
Brilliant! Thankyou!

On 24 Oct 2024, at 00:07, Steve Tarzia ***@***.***> wrote:
I’m I’m
﻿

Please update to the v3.2 version of the app which was posted this morning.
